version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: tonasket-wiki-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tonasket_wiki
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tonasket-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: tonasket-wiki-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tonasket.local
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - tonasket-network
    depends_on:
      - postgres

networks:
  tonasket-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
